//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaEntidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbProductos
    {
        public string Id { get; set; }
        public string Nombre { get; set; }
        public int Precio { get; set; }
        public Nullable<int> Impuesto { get; set; }
        public string Categoria { get; set; }
        public string Tamanno { get; set; }
        public Nullable<System.DateTime> FIngreso { get; set; }
        public Nullable<System.DateTime> FVenderAntes { get; set; }
        public Nullable<int> Estado { get; set; }
    }
}
